Update ressource cpu utilization in HPA to 50% & add HPA to nginx pod & add tests for nginx deployment

diff --git a/.github/workflows/app-ci-cd.yml b/.github/workflows/app-ci-cd.yml
--- a/.github/workflows/app-ci-cd.yml
+++ b/.github/workflows/app-ci-cd.yml
@@ -9,6 +9,7 @@ env:
   RNG_TEST_PORT: "30002"
   REDIS_TEST_PORT: "30003"
   WEBUI_TEST_PORT: "30004"
+  NGINX_TEST_PORT: "30005"
   GAR_LOCATION: europe-west1
   REPOSITORY: teolia-school-amineb
 
@@ -253,8 +254,34 @@ jobs:
             else
               echo "The smoke test against /json passed"  
           fi  
+
+  RunNginxSmokeTests:
+    needs: DeployTestingServices
+    name: Run nginx component smoke tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Run webui component integration tests
+        run: |
+          echo "Running Smoke Tests on the Nginx component"
+          response=$(curl -s -o /dev/null -w "%{http_code}"  http://${{ vars.SECOND_POOL_NODE_IP }}:${{ env.NGINX_TEST_PORT }}/)
+          if [[ $response != 200 && $response != 302 ]]
+            then
+              echo "Smoke test against the test deployment failed againt / endpoint with code ${response}"
+              exit 1
+          else
+            echo "The smoke test againt / passed"  
+          fi
+          response=$(curl -s -o /dev/null -w "%{http_code}"  http://${{ vars.SECOND_POOL_NODE_IP }}:${{ env.NGINX_TEST_PORT }}/json)
+          if [[ $response != 200 ]]
+            then
+              echo "Smoke test against the test deployment failed againt /json endpoint with code ${response}"
+              exit 1
+          else
+            echo "The smoke test against /json passed"  
+          fi  
+
   CleanUpTestDeployment:
-    needs: [RunHasherTests, RunRngTests, RunRedisServerTests,  RunWebUIIntegrationTests]
+    needs: [RunHasherTests, RunRngTests, RunRedisServerTests,  RunWebUIIntegrationTests, RunNginxSmokeTests]
     name: Delete the testing deployments and services
     runs-on: ubuntu-latest
     steps:       
@@ -287,16 +314,18 @@ jobs:
         kubectl delete deployment --namespace test rng-deployment-test
         kubectl delete deployment --namespace test worker-deployment-test
         kubectl delete deployment --namespace test webui-deployment-test
+        kubectl delete deployment --namespace test nginx-deployment-test
         # Delete services
         kubectl delete svc --namespace test hasher-test-service
         kubectl delete svc --namespace test redis-test-service
         kubectl delete svc --namespace test rng-test-service
         kubectl delete svc --namespace test webui-test-service
+        kubectl delete svc --namespace test nginx-test-service
         
   Deploy:
     name: Deploy production manifests to Kubernetes Cluster.
     runs-on: ubuntu-latest
-    needs: [BuildAndPushImage, RunHasherTests, RunRngTests, RunRedisServerTests,  RunWebUIIntegrationTests]
+    needs: [BuildAndPushImage, RunHasherTests, RunRngTests, RunRedisServerTests,  RunWebUIIntegrationTests, RunNginxSmokeTests]
     steps:
     - name: Checkout code
       uses: actions/checkout@master
